import express from "express";
import http from "http";
import cors from "cors";
import { Server } from "socket.io";
import { v4 as uuidv4 } from "uuid";
import dotenv from "dotenv";
import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

dotenv.config();

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: "*" } });

app.use(cors());
app.use(express.json());

// --- AWS SES setup ---
const sesRegion = process.env.AWS_REGION || process.env.AWS_SES_REGION || "us-east-1";
const sesClient = new SESClient({ region: sesRegion });

const DEFAULT_TO_EMAIL = process.env.AWS_SES_TO || "arjundevraj05@gmail.com";
const DEFAULT_FROM_EMAIL = process.env.AWS_SES_SENDER || DEFAULT_TO_EMAIL;

async function sendEmail({ subject, html, to = DEFAULT_TO_EMAIL, from = DEFAULT_FROM_EMAIL }) {
  const input = {
    Destination: { ToAddresses: [to] },
    Message: {
      Body: { Html: { Charset: "UTF-8", Data: html } },
      Subject: { Charset: "UTF-8", Data: subject },
    },
    Source: from,
  };
  const command = new SendEmailCommand(input);
  await sesClient.send(command);
}

app.post("/api/notify-email", async (req, res) => {
  const { role, status, amount, fromVpa, toVpa, txnId } = req.body || {};
  if (!role || !status || !amount || !fromVpa || !toVpa) {
    return res.status(400).json({ error: "Missing required fields" });
  }

  const succeeded = String(status).toUpperCase() === "SUCCESS";
  const contextTitle = role === "vendor" ? (succeeded ? "Payment Received" : "Payment Failed to Receive") : (succeeded ? "Payment Sent" : "Payment Failed to Send");
  const subject = `[SakhiPay] ${contextTitle}: ₹${amount} (${role})`;
  const html = `
    <div style="font-family: Arial, sans-serif; line-height: 1.6;">
      <h2>${contextTitle}</h2>
      <p><b>Role:</b> ${role}</p>
      <p><b>Status:</b> ${status}</p>
      <p><b>Amount:</b> ₹${amount}</p>
      <p><b>From VPA:</b> ${fromVpa}</p>
      <p><b>To VPA:</b> ${toVpa}</p>
      ${txnId ? `<p><b>Transaction ID:</b> ${txnId}</p>` : ""}
      <hr/>
      <p style="color:#666;">This email was generated by SakhiPay UPI Simulation.</p>
    </div>
  `;

  try {
    await sendEmail({ subject, html });
    res.json({ ok: true });
  } catch (err) {
    console.error("SES sendEmail error", err);
    res.status(500).json({ error: "Failed to send email" });
  }
});

// --- AWS S3 presign for direct browser uploads ---
const s3Region = process.env.AWS_REGION || process.env.AWS_S3_REGION || "us-east-1";
const s3Bucket = process.env.AWS_S3_BUCKET;
const s3Client = new S3Client({ region: s3Region });

// Upload file directly through API server (no CORS issues)
app.post("/api/s3/upload", async (req, res) => {
  try {
    if (!s3Bucket) return res.status(500).json({ error: "Missing AWS_S3_BUCKET" });
    
    // This would need multipart/form-data handling
    // For now, let's keep the presign approach but fix CORS
    res.status(501).json({ error: "Direct upload not implemented yet. Please configure S3 CORS." });
  } catch (err) {
    console.error("S3 upload error", err);
    res.status(500).json({ error: "Failed to upload file" });
  }
});

app.get("/api/s3/presign", async (req, res) => {
  try {
    if (!s3Bucket) return res.status(500).json({ error: "Missing AWS_S3_BUCKET" });
    const { filename, contentType } = req.query;
    if (!filename || !contentType) return res.status(400).json({ error: "filename and contentType are required" });

    const objectKey = `receipts/${Date.now()}-${encodeURIComponent(String(filename))}`;
    const command = new PutObjectCommand({
      Bucket: s3Bucket,
      Key: objectKey,
      ContentType: String(contentType),
      ACL: "public-read",
    });
    const url = await getSignedUrl(s3Client, command, { expiresIn: 60 });
    const publicUrl = `https://${s3Bucket}.s3.${s3Region}.amazonaws.com/${objectKey}`;
    return res.json({ url, key: objectKey, publicUrl });
  } catch (err) {
    console.error("S3 presign error", err);
    res.status(500).json({ error: "Failed to generate presigned URL" });
  }
});

const users = {
  "arjun@sakhipay": { name: "Arjun", balance: 2500 },
  "eshita@sakhipay": { name: "Eshita", balance: 1800 },
};
const txns = {};

// register
app.post("/api/register", (req, res) => {
  const { vpa, name } = req.body;
  users[vpa] = { name, balance: 2000 };
  res.json({ ok: true });
});

// initiate txn
app.post("/api/txn/initiate", (req, res) => {
  const { fromVpa, toVpa, amount } = req.body;
  if (!users[fromVpa] || !users[toVpa])
    return res.status(400).json({ error: "Invalid VPA" });

  const txnId = uuidv4();
  txns[txnId] = { txnId, fromVpa, toVpa, amount, status: "PENDING" };
  res.json({ txnId, status: "PENDING" });
});

// verify PIN
app.post("/api/txn/verify-pin", (req, res) => {
  const { txnId, pin } = req.body;
  const txn = txns[txnId];
  if (!txn) return res.status(404).json({ error: "Invalid txn" });

  setTimeout(() => {
    if (pin === "1234" && users[txn.fromVpa].balance >= txn.amount) {
      users[txn.fromVpa].balance -= txn.amount;
      users[txn.toVpa].balance += txn.amount;
      txn.status = "SUCCESS";
      io.emit("txn:update", { txnId, status: "SUCCESS" });
    } else {
      txn.status = "FAILED";
      io.emit("txn:update", { txnId, status: "FAILED" });
    }
  }, 2000);

  res.json({ status: "PROCESSING" });
});

// get balances
app.get("/api/balance/:vpa", (req, res) => {
  res.json(users[req.params.vpa] || {});
});

server.listen(4000, () => console.log("UPI Simulator API running on 4000"));
