import express from "express";
import http from "http";
import cors from "cors";
import { Server } from "socket.io";
import { v4 as uuidv4 } from "uuid";
import dotenv from "dotenv";
import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { InferenceClient } from "@huggingface/inference";
import nodemailer from "nodemailer";

dotenv.config();

const PORT = Number(process.env.PORT) || 4000;
const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: "*" } });

app.use(cors());
app.use(express.json({ limit: "2mb" }));

const sesRegion = process.env.AWS_REGION || process.env.AWS_SES_REGION || "us-east-1";
const sesClient = new SESClient({
  region: sesRegion,
  credentials:
    process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY
      ? {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        }
      : undefined,
});

const DEFAULT_TO_EMAIL = process.env.AWS_SES_TO || "arjundevraj05@gmail.com";
const DEFAULT_FROM_EMAIL = process.env.AWS_SES_SENDER || DEFAULT_TO_EMAIL;

const hasAwsCredentials =
  Boolean(process.env.AWS_ACCESS_KEY_ID) &&
  process.env.AWS_ACCESS_KEY_ID !== "your-access-key" &&
  Boolean(process.env.AWS_SECRET_ACCESS_KEY) &&
  process.env.AWS_SECRET_ACCESS_KEY !== "your-secret-key";

const hasGmailCredentials =
  Boolean(process.env.GMAIL_USER) &&
  process.env.GMAIL_USER !== "your-email@gmail.com" &&
  Boolean(process.env.GMAIL_APP_PASSWORD) &&
  process.env.GMAIL_APP_PASSWORD !== "your-app-password";

const gmailTransporter = hasGmailCredentials
  ? nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD,
      },
    })
  : null;

function simulateEmail({ subject, html, to }) {
  console.log("\n" + "=".repeat(60));
  console.log("EMAIL NOTIFICATION (simulated)");
  console.log("=".repeat(60));
  console.log(`To: ${to}`);
  console.log(`Subject: ${subject}`);
  console.log(html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim());
  console.log("=".repeat(60) + "\n");
  return { MessageId: `simulated-${Date.now()}` };
}

async function sendEmail({ subject, html, to = DEFAULT_TO_EMAIL, from = DEFAULT_FROM_EMAIL }) {
  if (gmailTransporter) {
    try {
      const result = await gmailTransporter.sendMail({ from, to, subject, html });
      console.log("Email sent via Gmail:", result.messageId);
      return result;
    } catch (error) {
      console.error("Gmail send failed:", error.message);
    }
  }

  if (hasAwsCredentials) {
    try {
      const command = new SendEmailCommand({
        Destination: { ToAddresses: [to] },
        Message: {
          Body: { Html: { Charset: "UTF-8", Data: html } },
          Subject: { Charset: "UTF-8", Data: subject },
        },
        Source: from,
      });
      const result = await sesClient.send(command);
      console.log("Email sent via SES:", result.MessageId);
      return result;
    } catch (error) {
      console.error("SES send failed:", error.message);
    }
  }

  return simulateEmail({ subject, html, to });
}

app.get("/api/health", (_req, res) => {
  res.json({
    ok: true,
    service: "SakhiPay API",
    port: PORT,
    email: hasGmailCredentials ? "gmail" : hasAwsCredentials ? "ses" : "simulated",
    s3: Boolean(process.env.AWS_S3_BUCKET),
    huggingface: Boolean(
      process.env.HUGGINGFACE_API_KEY || process.env.REACT_APP_HUGGINGFACE_API_KEY
    ),
  });
});

app.post("/api/notify-email", async (req, res) => {
  const { role, status, amount, fromVpa, toVpa, txnId } = req.body || {};
  if (!role || !status || !amount || !fromVpa || !toVpa) {
    return res.status(400).json({ error: "Missing required fields" });
  }

  const succeeded = String(status).toUpperCase() === "SUCCESS";
  const contextTitle =
    role === "vendor"
      ? succeeded
        ? "Payment Received"
        : "Payment Failed to Receive"
      : succeeded
        ? "Payment Sent"
        : "Payment Failed to Send";
  const subject = `[SakhiPay] ${contextTitle}: ₹${amount} (${role})`;
  const html = `
    <div style="font-family: Arial, sans-serif; line-height: 1.6;">
      <h2>${contextTitle}</h2>
      <p><b>Role:</b> ${role}</p>
      <p><b>Status:</b> ${status}</p>
      <p><b>Amount:</b> ₹${amount}</p>
      <p><b>From VPA:</b> ${fromVpa}</p>
      <p><b>To VPA:</b> ${toVpa}</p>
      ${txnId ? `<p><b>Transaction ID:</b> ${txnId}</p>` : ""}
      <hr/>
      <p style="color:#666;">This email was generated by SakhiPay UPI Simulation.</p>
    </div>
  `;

  try {
    await sendEmail({ subject, html });
    res.json({ ok: true });
  } catch (err) {
    console.error("notify-email error", err);
    res.status(500).json({ error: "Failed to send email" });
  }
});

const s3Region = process.env.AWS_REGION || process.env.AWS_S3_REGION || "us-east-1";
const s3Bucket = process.env.AWS_S3_BUCKET;
const s3Client = new S3Client({
  region: s3Region,
  credentials: hasAwsCredentials
    ? {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      }
    : undefined,
});

app.get("/api/s3/presign", async (req, res) => {
  try {
    if (!s3Bucket || !hasAwsCredentials) {
      return res.status(503).json({
        error:
          "S3 is not configured. Set AWS_S3_BUCKET, AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY, or use local receipt preview.",
      });
    }

    const { filename, contentType } = req.query;
    if (!filename || !contentType) {
      return res.status(400).json({ error: "filename and contentType are required" });
    }

    const objectKey = `receipts/${Date.now()}-${encodeURIComponent(String(filename))}`;
    const command = new PutObjectCommand({
      Bucket: s3Bucket,
      Key: objectKey,
      ContentType: String(contentType),
    });
    const url = await getSignedUrl(s3Client, command, { expiresIn: 60 });
    const publicUrl = `https://${s3Bucket}.s3.${s3Region}.amazonaws.com/${objectKey}`;
    return res.json({ url, key: objectKey, publicUrl });
  } catch (err) {
    console.error("S3 presign error", err);
    res.status(500).json({ error: "Failed to generate presigned URL" });
  }
});

const HUGGING_FACE_API_KEY =
  process.env.HUGGINGFACE_API_KEY ||
  process.env.REACT_APP_HUGGINGFACE_API_KEY ||
  process.env.NEXT_PUBLIC_HUGGINGFACE_API_KEY;
const hfClient = HUGGING_FACE_API_KEY ? new InferenceClient(HUGGING_FACE_API_KEY) : null;

function localExpenseSentiment(text) {
  const lower = text.toLowerCase();
  const negativeHints = ["debt", "loan", "overspend", "stress", "urgent", "borrow", "emi"];
  const positiveHints = ["save", "saved", "budget", "invest", "surplus", "careful"];
  const negativeHits = negativeHints.filter((w) => lower.includes(w)).length;
  const positiveHits = positiveHints.filter((w) => lower.includes(w)).length;

  if (negativeHits > positiveHits) {
    return {
      sentiment: "negative",
      score: 0.72,
      analysis:
        "Your expenses might indicate financial stress. Try tracking and optimizing your spending.",
    };
  }
  if (positiveHits > negativeHits) {
    return {
      sentiment: "positive",
      score: 0.74,
      analysis:
        "Your spending behavior looks positive! It indicates a well-balanced financial approach.",
    };
  }
  return {
    sentiment: "neutral",
    score: 0.66,
    analysis:
      "Your spending pattern is stable. Consider reviewing it periodically for financial health.",
  };
}

app.post("/api/analyze-expenses", async (req, res) => {
  try {
    const { text } = req.body || {};
    if (!text || typeof text !== "string" || text.trim().length === 0) {
      return res.status(400).json({ error: "Expense text is required for analysis." });
    }

    if (!hfClient) {
      return res.json(localExpenseSentiment(text));
    }

    const data = await hfClient.textClassification({
      model: "ProsusAI/finbert",
      inputs: text,
    });

    if (!Array.isArray(data) || data.length === 0) {
      return res.status(502).json({ error: "Invalid response format from FinBERT." });
    }

    const highestConfidenceSentiment = data.reduce((prev, curr) =>
      prev.score > curr.score ? prev : curr
    );

    let sentimentDescription = "";
    switch (highestConfidenceSentiment?.label) {
      case "positive":
        sentimentDescription =
          "Your spending behavior looks positive! It indicates a well-balanced financial approach.";
        break;
      case "neutral":
        sentimentDescription =
          "Your spending pattern is stable. Consider reviewing it periodically for financial health.";
        break;
      case "negative":
        sentimentDescription =
          "Your expenses might indicate financial stress. Try tracking and optimizing your spending.";
        break;
      default:
        sentimentDescription =
          "Analysis inconclusive. Try adding more expenses for better insights.";
    }

    return res.json({
      sentiment: highestConfidenceSentiment?.label || "unknown",
      score: highestConfidenceSentiment?.score ?? 0,
      analysis: sentimentDescription,
    });
  } catch (error) {
    console.error("analyze-expenses error:", error.message);
    const fallback = localExpenseSentiment(String(req.body?.text || ""));
    return res.json({ ...fallback, note: "Used local fallback after FinBERT error." });
  }
});

const users = {
  "arjun@sakhipay": { name: "Arjun", balance: 2500, email: "arjundevraj05@gmail.com" },
  "eshita@sakhipay": { name: "Eshita", balance: 1800, email: "arjundevraj05@gmail.com" },
};
const txns = {};

app.post("/api/register", (req, res) => {
  const { vpa, name, email } = req.body || {};
  if (!vpa || !name) return res.status(400).json({ error: "vpa and name are required" });
  users[vpa] = { name, balance: 2000, email: email || `${name.toLowerCase()}@example.com` };
  res.json({ ok: true });
});

app.post("/api/txn/initiate", (req, res) => {
  const { fromVpa, toVpa, amount } = req.body || {};
  if (!users[fromVpa] || !users[toVpa]) {
    return res.status(400).json({ error: "Invalid VPA" });
  }

  const txnId = uuidv4();
  txns[txnId] = { txnId, fromVpa, toVpa, amount: Number(amount), status: "PENDING" };
  res.json({ txnId, status: "PENDING" });
});

app.post("/api/txn/verify-pin", async (req, res) => {
  const { txnId, pin } = req.body || {};
  const txn = txns[txnId];
  if (!txn) return res.status(404).json({ error: "Invalid txn" });

  setTimeout(async () => {
    if (pin === "1234" && users[txn.fromVpa].balance >= txn.amount) {
      users[txn.fromVpa].balance -= txn.amount;
      users[txn.toVpa].balance += txn.amount;
      txn.status = "SUCCESS";
      io.emit("txn:update", { txnId, status: "SUCCESS" });

      try {
        await sendEmail({
          subject: `Payment Confirmation - SakhiPay`,
          html: `<p>Payment of ₹${txn.amount} from ${txn.fromVpa} to ${txn.toVpa} succeeded. Txn: ${txnId}</p>`,
          to: users[txn.fromVpa].email,
        });
      } catch (emailError) {
        console.error("Failed to send txn email:", emailError.message);
      }
    } else {
      txn.status = "FAILED";
      io.emit("txn:update", { txnId, status: "FAILED" });
    }
  }, 2000);

  res.json({ status: "PROCESSING" });
});

app.get("/api/balance/:vpa", (req, res) => {
  res.json(users[req.params.vpa] || {});
});

server.listen(PORT, () => {
  console.log(`SakhiPay API running on http://localhost:${PORT}`);
});
